import type { ITheme } from "xterm";

export interface TerminalThemeDef {
  id: string;
  label: string;
  theme: ITheme;
}

// Paletas reales de terminal, no inventadas — las mismas cuatro que
// cualquiera con una config de dotfiles termina probando tarde o temprano,
// mas el rojo/negro que ya trae KRYPTOS por defecto.
export const TERMINAL_THEMES: TerminalThemeDef[] = [
  {
    id: "kryptos",
    label: "KRYPTOS (por defecto)",
    theme: {
      background: "#00000000",
      foreground: "#FF5B5B",
      cursor: "#FF3B3B",
      cursorAccent: "#050505",
      selectionBackground: "rgba(255, 59, 59, 0.28)",
      black: "#0A0A0A",
      red: "#FF3B3B",
      green: "#00D26A",
      yellow: "#FFB020",
      blue: "#5B9BFF",
      magenta: "#C77DFF",
      cyan: "#3BD1D6",
      white: "#EAEAEA",
      brightBlack: "#5C5C5C",
      brightRed: "#FF6B6B",
      brightGreen: "#3EE58F",
      brightYellow: "#FFC94D",
      brightBlue: "#84B4FF",
      brightMagenta: "#D9A6FF",
      brightCyan: "#6FE0E4",
      brightWhite: "#FFFFFF",
    },
  },
  {
    id: "matrix",
    label: "Matrix",
    theme: {
      background: "#00000000",
      foreground: "#00FF41",
      cursor: "#00FF41",
      cursorAccent: "#000000",
      selectionBackground: "rgba(0, 255, 65, 0.25)",
      black: "#001a00",
      red: "#00cc33",
      green: "#00FF41",
      yellow: "#5fff5f",
      blue: "#00994d",
      magenta: "#00b36b",
      cyan: "#33ff77",
      white: "#c8ffcf",
      brightBlack: "#004d00",
      brightRed: "#00e639",
      brightGreen: "#66ff85",
      brightYellow: "#a3ffb8",
      brightBlue: "#33cc70",
      brightMagenta: "#5fffb0",
      brightCyan: "#99ffcc",
      brightWhite: "#e6ffe9",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    theme: {
      background: "#00000000",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "rgba(189, 147, 249, 0.3)",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "nord",
    label: "Nord",
    theme: {
      background: "#00000000",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      cursorAccent: "#2e3440",
      selectionBackground: "rgba(136, 192, 208, 0.3)",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    id: "gruvbox",
    label: "Gruvbox",
    theme: {
      background: "#00000000",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "rgba(250, 189, 47, 0.25)",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    id: "amber",
    label: "Ambar CRT",
    theme: {
      background: "#0d0700",
      foreground: "#ffb000",
      cursor: "#ffb000",
      cursorAccent: "#0d0700",
      selectionBackground: "rgba(255, 176, 0, 0.3)",
      black: "#2a1c00",
      red: "#ffb000",
      green: "#ffb000",
      yellow: "#ffcf5c",
      blue: "#cc8c00",
      magenta: "#e6a100",
      cyan: "#ffcf5c",
      white: "#ffd98c",
      brightBlack: "#4d3400",
      brightRed: "#ffcf5c",
      brightGreen: "#ffcf5c",
      brightYellow: "#ffe29e",
      brightBlue: "#e6a100",
      brightMagenta: "#ffb000",
      brightCyan: "#ffe29e",
      brightWhite: "#fff3d6",
    },
  },
];

export const DEFAULT_TERMINAL_THEME_ID = "kryptos";

export function getTerminalTheme(id: string | undefined | null): ITheme {
  return TERMINAL_THEMES.find((t) => t.id === id)?.theme ?? TERMINAL_THEMES[0].theme;
}
